### ISSUE TITLE
.emit method not sending in realtime

### ISSUE THREAD

**Issue by petethomasmusique** [iccmr-quantum/SOC-Qasm#9]
So! Everything is working pretty nicely, with successful results and comms between browser and python - for various different qasm backends.

The issue is to do with the .emit method - and the issue may be with the browser, but I thought I'd raise it here.

When I run a job, I can see various messages being printed in the terminal, e.g.
```
Running circuit on ibmq_santiago...
Job Status: job is being validated
Job Status: job is actively running
Job Status: job has successfully run
```

These are printed sequentially, as soon as the job monitor has a notification, with a few seconds delay between each, as the job progresses.

However, these do not come through the websocket to the browser until the entire job has completed - at which point all of the messages arrive at once. Not a big issue, but interesting to unpick where the hold up is occuring.

**Comment by omarcostahamido** [comment]
Thx for the report @petethomasmusique .
You're right, all the emit messages triggered inside a `@sio.event` are only sent at the end.
I currently don't have a better solution but not to rely on these `job_monitor` reports.
Feel free to propose a PR with another fix.

**Comment by petethomasmusique** [comment]
@omarcostahamido OK. Good to have confirmation that the issue resides at the Python end. I'll give it some thought.
